# -*- coding: utf-8 -*- 

# 错误码定义

OK = 0 # 正常

ERR_UNKNOWN             = 10000 # 未知异常

ERR_UID_INVALID         = 10001 # UID非法
ERR_VIDEO_ID_INVALID    = 10002 # 视频ID非法

ERR_DATA_NOT_FOUND      = 40001 # 数据未找到

# 视频表的列定义
TAB_VIDEO_COL_ID            = 0
TAB_VIDEO_COL_NAME_EN       = 1
TAB_VIDEO_COL_NAME_CH       = 2
TAB_VIDEO_COL_POSTER        = 3
TAB_VIDEO_COL_DURATION      = 4
TAB_VIDEO_COL_URL           = 5
TAB_VIDEO_COL_WORDS_SCRIPT  = 6
TAB_VIDEO_COL_WORDS         = 7
TAB_VIDEO_COL_DEFINITION    = 8

# 账户表的列定义
TAB_ACCOUNT_COL_ID            = 0
TAB_ACCOUNT_COL_NICKNAME      = 1
TAB_ACCOUNT_COL_GENDER        = 2
TAB_ACCOUNT_COL_AVATAR        = 3
TAB_ACCOUNT_COL_COUNTRY       = 4
TAB_ACCOUNT_COL_PROVINCE      = 5
TAB_ACCOUNT_COL_CITY          = 6
TAB_ACCOUNT_COL_WX_OPENID     = 7
TAB_ACCOUNT_COL_CHILD_AGE     = 8
TAB_ACCOUNT_COL_CHILD_GENDER  = 10
TAB_ACCOUNT_COL_TIME_SETTING  = 11

# 统计表的列定义
TAB_STATISTIC_COL_ID            = 0
TAB_STATISTIC_COL_UID           = 1
TAB_STATISTIC_COL_TIME          = 2
TAB_STATISTIC_COL_VIDEOS        = 3
TAB_STATISTIC_COL_WORDS         = 4
TAB_STATISTIC_COL_DAYS          = 5
TAB_STATISTIC_COL_SCORE         = 6
